package link.vo;

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * COMPANY 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Company implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** COMPID. */
	private String compid;

	/** COMPPASSWORD. */
	private String comppassword;

	/** COMPNAME. */
	private String compname;

	/** COMPADDRESS. */
	private String compaddress;

	/** COMPAREA. */
	private String comparea;

	/** COMPSIZE. */
	private int compsize;

	/** COMPVALID. */
	private String compvalid;

	/** COMPPHONE. */
	private String compphone;

	/** COMPNUM. */
	private String compnum;

	/** CULTURE 목록. */
	private Set<Culture> cultureSet;

	/** JOB 목록. */
	private Set<Job> jobSet;

	/**
	 * 생성자.
	 */


	/**
	 * COMPID을 설정합니다..
	 * 
	 * @param compid
	 *            COMPID
	 */
	public Company(){
		
	}

	public Company(String compid, String comppassword, String compname, String comparea,
			int compsize) {
		this.compid = compid;
		this.comppassword = comppassword;
		this.compname = compname;
		this.comparea = comparea;
		this.compsize = compsize;
	}
	
	
	
	public Company(String compid, String comppassword, String compname, String compaddress, String comparea,
			int compsize, String compvalid, String compphone, String compnum) {
		super();
		this.compid = compid;
		this.comppassword = comppassword;
		this.compname = compname;
		this.compaddress = compaddress;
		this.comparea = comparea;
		this.compsize = compsize;
		this.compvalid = compvalid;
		this.compphone = compphone;
		this.compnum = compnum;
	}



	public String getCompid() {
		return compid;
	}

	public void setCompid(String compid) {
		this.compid = compid;
	}

	/**
	 * COMPPASSWORD을 설정합니다..
	 * 
	 * @param comppassword
	 *            COMPPASSWORD
	 */
	public void setComppassword(String comppassword) {
		this.comppassword = comppassword;
	}

	/**
	 * COMPPASSWORD을 가져옵니다..
	 * 
	 * @return COMPPASSWORD
	 */
	public String getComppassword() {
		return this.comppassword;
	}

	/**
	 * COMPNAME을 설정합니다..
	 * 
	 * @param compname
	 *            COMPNAME
	 */
	public void setCompname(String compname) {
		this.compname = compname;
	}

	/**
	 * COMPNAME을 가져옵니다..
	 * 
	 * @return COMPNAME
	 */
	public String getCompname() {
		return this.compname;
	}

	/**
	 * COMPADDRESS을 설정합니다..
	 * 
	 * @param compaddress
	 *            COMPADDRESS
	 */
	public void setCompaddress(String compaddress) {
		this.compaddress = compaddress;
	}

	/**
	 * COMPADDRESS을 가져옵니다..
	 * 
	 * @return COMPADDRESS
	 */
	public String getCompaddress() {
		return this.compaddress;
	}

	/**
	 * COMPAREA을 설정합니다..
	 * 
	 * @param comparea
	 *            COMPAREA
	 */
	public void setComparea(String comparea) {
		this.comparea = comparea;
	}

	/**
	 * COMPAREA을 가져옵니다..
	 * 
	 * @return COMPAREA
	 */
	public String getComparea() {
		return this.comparea;
	}


	public int getCompsize() {
		return compsize;
	}

	public void setCompsize(int compsize) {
		this.compsize = compsize;
	}

	/**
	 * COMPVALID을 설정합니다..
	 * 
	 * @param compvalid
	 *            COMPVALID
	 */
	public void setCompvalid(String compvalid) {
		this.compvalid = compvalid;
	}

	/**
	 * COMPVALID을 가져옵니다..
	 * 
	 * @return COMPVALID
	 */
	public String getCompvalid() {
		return this.compvalid;
	}

	/**
	 * COMPPHONE을 설정합니다..
	 * 
	 * @param compphone
	 *            COMPPHONE
	 */
	public void setCompphone(String compphone) {
		this.compphone = compphone;
	}

	/**
	 * COMPPHONE을 가져옵니다..
	 * 
	 * @return COMPPHONE
	 */
	public String getCompphone() {
		return this.compphone;
	}

	/**
	 * COMPNUM을 설정합니다..
	 * 
	 * @param compnum
	 *            COMPNUM
	 */
	public void setCompnum(String compnum) {
		this.compnum = compnum;
	}

	/**
	 * COMPNUM을 가져옵니다..
	 * 
	 * @return COMPNUM
	 */
	public String getCompnum() {
		return this.compnum;
	}

	/**
	 * CULTURE 목록을 설정합니다..
	 * 
	 * @param cultureSet
	 *            CULTURE 목록
	 */
	public void setCultureSet(Set<Culture> cultureSet) {
		this.cultureSet = cultureSet;
	}

	/**
	 * CULTURE를 추가합니다..
	 * 
	 * @param culture
	 *            CULTURE
	 */
	public void addCulture(Culture culture) {
		this.cultureSet.add(culture);
	}

	/**
	 * CULTURE 목록을 가져옵니다..
	 * 
	 * @return CULTURE 목록
	 */
	public Set<Culture> getCultureSet() {
		return this.cultureSet;
	}

	/**
	 * JOB 목록을 설정합니다..
	 * 
	 * @param jobSet
	 *            JOB 목록
	 */
	public void setJobSet(Set<Job> jobSet) {
		this.jobSet = jobSet;
	}

	/**
	 * JOB를 추가합니다..
	 * 
	 * @param job
	 *            JOB
	 */
	public void addJob(Job job) {
		this.jobSet.add(job);
	}

	/**
	 * JOB 목록을 가져옵니다..
	 * 
	 * @return JOB 목록
	 */
	public Set<Job> getJobSet() {
		return this.jobSet;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((compid == null) ? 0 : compid.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		Company other = (Company) obj;
		if (compid == null) {
			if (other.compid != null) {
				return false;
			}
		} else if (!compid.equals(other.compid)) {
			return false;
		}
		return true;
	}

	@Override
	public String toString() {
		return "Company [compid=" + compid + ", comppassword=" + comppassword + ", compname=" + compname
				+ ", compaddress=" + compaddress + ", comparea=" + comparea + ", compsize=" + compsize + ", compvalid="
				+ compvalid + ", compphone=" + compphone + ", compnum=" + compnum + ", cultureSet=" + cultureSet
				+ ", jobSet=" + jobSet + "]";
	}
	
	
	
	

}
