package link.vo;

import java.io.Serializable;
import java.util.Date;

/**
 * EDUCATION 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Education implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 개인유저. */
	private String applicantid;

	/** NAME. */
	private String name;

	/** MAJOR. */
	private String major;

	/** MINOR. */
	private String minor;

	/** DIPLOMA. */
	private String diploma;

	/** startdate. */
	private String startdate;

	/** enddate. */
	private String enddate;

	/**
	 * 생성자.
	 */
	public Education() {
	}

	
	public Education(String applicantid, String name, String major, String minor, String diploma, String startdate,
			String enddate) {
		super();
		this.applicantid = applicantid;
		this.name = name;
		this.major = major;
		this.minor = minor;
		this.diploma = diploma;
		this.startdate = startdate;
		this.enddate = enddate;
	}


	/**
	 * 개인유저을 설정합니다..
	 * 
	 * @param applicant
	 *            개인유저
	 */
	public void setApplicantid(String applicantid) {
		this.applicantid = applicantid;
	}

	/**
	 * 개인유저을 가져옵니다..
	 * 
	 * @return 개인유저
	 */
	public String getApplicantid() {
		return this.applicantid;
	}

	/**
	 * NAME을 설정합니다..
	 * 
	 * @param name
	 *            NAME
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * NAME을 가져옵니다..
	 * 
	 * @return NAME
	 */
	public String getName() {
		return this.name;
	}

	/**
	 * MAJOR을 설정합니다..
	 * 
	 * @param major
	 *            MAJOR
	 */
	public void setMajor(String major) {
		this.major = major;
	}

	/**
	 * MAJOR을 가져옵니다..
	 * 
	 * @return MAJOR
	 */
	public String getMajor() {
		return this.major;
	}

	/**
	 * MINOR을 설정합니다..
	 * 
	 * @param minor
	 *            MINOR
	 */
	public void setMinor(String minor) {
		this.minor = minor;
	}

	/**
	 * MINOR을 가져옵니다..
	 * 
	 * @return MINOR
	 */
	public String getMinor() {
		return this.minor;
	}

	/**
	 * DIPLOMA을 설정합니다..
	 * 
	 * @param diploma
	 *            DIPLOMA
	 */
	public void setDiploma(String diploma) {
		this.diploma = diploma;
	}

	/**
	 * DIPLOMA을 가져옵니다..
	 * 
	 * @return DIPLOMA
	 */
	public String getDiploma() {
		return this.diploma;
	}

	/**
	 * startdate을 설정합니다..
	 * 
	 * @param startdate
	 *            startdate
	 */
	public void setStartdate(String startdate) {
		this.startdate = startdate;
	}

	/**
	 * startdate을 가져옵니다..
	 * 
	 * @return startdate
	 */
	public String getStartdate() {
		return this.startdate;
	}

	/**
	 * enddate을 설정합니다..
	 * 
	 * @param enddate
	 *            enddate
	 */
	public void setEnddate(String enddate) {
		this.enddate = enddate;
	}

	/**
	 * enddate을 가져옵니다..
	 * 
	 * @return enddate
	 */
	public String getEnddate() {
		return this.enddate;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((applicantid == null) ? 0 : applicantid.hashCode());
		result = prime * result + ((name == null) ? 0 : name.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		Education other = (Education) obj;
		if (applicantid == null) {
			if (other.applicantid != null) {
				return false;
			}
		} else if (!applicantid.equals(other.applicantid)) {
			return false;
		}
		if (name == null) {
			if (other.name != null) {
				return false;
			}
		} else if (!name.equals(other.name)) {
			return false;
		}
		return true;
	}


	@Override
	public String toString() {
		return "Education [applicantid=" + applicantid + ", name=" + name + ", major=" + major + ", minor=" + minor
				+ ", diploma=" + diploma + ", startdate=" + startdate + ", enddate=" + enddate + "]";
	}
	
}
