package link.vo;

import java.io.Serializable;
import java.util.Date;

/**
 * Experience 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Experience implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 개인유저. */
	private String applicantid;

	/** workname. */
	private String workname;

	/** workjobtitle. */
	private String workjobtitle;

	/** startdate. */
	private String startdate;

	/** enddate. */
	private String enddate;

	/**
	 * 생성자.
	 */
	public Experience() {
	}

	/**
	 * 개인유저을 설정합니다..
	 * 
	 * @param applicant
	 *            개인유저
	 */
	public void setApplicantid(String applicantid) {
		this.applicantid = applicantid;
	}

	/**
	 * 개인유저을 가져옵니다..
	 * 
	 * @return 개인유저
	 */
	public String getApplicantid() {
		return this.applicantid;
	}

	/**
	 * workname을 설정합니다..
	 * 
	 * @param workname
	 *            workname
	 */
	public void setWorkname(String workname) {
		this.workname = workname;
	}

	/**
	 * workname을 가져옵니다..
	 * 
	 * @return workname
	 */
	public String getWorkname() {
		return this.workname;
	}

	/**
	 * workjobtitle을 설정합니다..
	 * 
	 * @param workjobtitle
	 *            workjobtitle
	 */
	public void setWorkjobtitle(String workjobtitle) {
		this.workjobtitle = workjobtitle;
	}

	/**
	 * workjobtitle을 가져옵니다..
	 * 
	 * @return workjobtitle
	 */
	public String getWorkjobtitle() {
		return this.workjobtitle;
	}

	/**
	 * startdate을 설정합니다..
	 * 
	 * @param startdate
	 *            startdate
	 */
	public void setStartdate(String startdate) {
		this.startdate = startdate;
	}

	/**
	 * startdate을 가져옵니다..
	 * 
	 * @return startdate
	 */
	public String getStartdate() {
		return this.startdate;
	}

	/**
	 * enddate을 설정합니다..
	 * 
	 * @param enddate
	 *            enddate
	 */
	public void setEnddate(String enddate) {
		this.enddate = enddate;
	}

	/**
	 * enddate을 가져옵니다..
	 * 
	 * @return enddate
	 */
	public String getEnddate() {
		return this.enddate;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((applicantid == null) ? 0 : applicantid.hashCode());
		result = prime * result + ((workname == null) ? 0 : workname.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		Experience other = (Experience) obj;
		if (applicantid == null) {
			if (other.applicantid != null) {
				return false;
			}
		} else if (!applicantid.equals(other.applicantid)) {
			return false;
		}
		if (workname == null) {
			if (other.workname != null) {
				return false;
			}
		} else if (!workname.equals(other.workname)) {
			return false;
		}
		return true;
	}

	@Override
	public String toString() {
		return "Experience [applicantid=" + applicantid + ", workname=" + workname + ", workjobtitle=" + workjobtitle
				+ ", startdate=" + startdate + ", enddate=" + enddate + "]";
	}
	
}
