package link.vo;

import java.io.Serializable;

/**
 * MATCHING 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Matching implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 개인유저. */
	private String applicantid;

	/** JOB. */
	private String jobid;

	/** culper. */
	private Double culper;

	/** skillper. */
	private Double skillper;

	/** perper. */
	private Double perper;

	/** totalper. */
	private Double totalper;

	/** status. */
	private String status;

	/**
	 * 생성자.
	 */
	public Matching() {}

	/**
	 * 개인유저을 설정합니다..
	 * 
	 * @param applicant
	 *            개인유저
	 */
	public void setApplicantid(String applicantid) {
		this.applicantid = applicantid;
	}

	/**
	 * 개인유저을 가져옵니다..
	 * 
	 * @return 개인유저
	 */
	public String getApplicantid() {
		return this.applicantid;
	}

	/**
	 * JOB을 설정합니다..
	 * 
	 * @param job
	 *            JOB
	 */
	public void setJobid(String jobid) {
		this.jobid = jobid;
	}

	/**
	 * JOB을 가져옵니다..
	 * 
	 * @return JOB
	 */
	public String getJobid() {
		return this.jobid;
	}

	/**
	 * culper을 설정합니다..
	 * 
	 * @param culper
	 *            culper
	 */
	public void setCulper(Double culper) {
		this.culper = culper;
	}

	/**
	 * culper을 가져옵니다..
	 * 
	 * @return culper
	 */
	public Double getCulper() {
		return this.culper;
	}

	/**
	 * skillper을 설정합니다..
	 * 
	 * @param skillper
	 *            skillper
	 */
	public void setSkillper(Double skillper) {
		this.skillper = skillper;
	}

	/**
	 * skillper을 가져옵니다..
	 * 
	 * @return skillper
	 */
	public Double getSkillper() {
		return this.skillper;
	}

	/**
	 * perper을 설정합니다..
	 * 
	 * @param perper
	 *            perper
	 */
	public void setPerper(Double perper) {
		this.perper = perper;
	}

	/**
	 * perper을 가져옵니다..
	 * 
	 * @return perper
	 */
	public Double getPerper() {
		return this.perper;
	}

	/**
	 * totalper을 설정합니다..
	 * 
	 * @param totalper
	 *            totalper
	 */
	public void setTotalper(Double totalper) {
		this.totalper = totalper;
	}

	/**
	 * totalper을 가져옵니다..
	 * 
	 * @return totalper
	 */
	public Double getTotalper() {
		return this.totalper;
	}

	/**
	 * status을 설정합니다..
	 * 
	 * @param status
	 *            status
	 */
	public void setStatus(String status) {
		this.status = status;
	}

	/**
	 * status을 가져옵니다..
	 * 
	 * @return status
	 */
	public String getStatus() {
		return this.status;
	}

	

	@Override
	public String toString() {
		return "Matching [applicantid=" + applicantid + ", jobid=" + jobid + ", culper=" + culper + ", skillper=" + skillper
				+ ", perper=" + perper + ", totalper=" + totalper + ", status=" + status + "]";
	}
	
}
