package link.vo;

import java.io.Serializable;

/**
 * PERSONALITY 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Personality implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** PER_ID. */
	private String perId;

	/** JOB. */
	private String jobid;

	/** 개인유저. */
	private String applicantid;

	/** Agreeableness. */
	private Double agreeableness;

	/** Conscientiousness. */
	private Double conscientiousness;

	/** Extraversion. */
	private Double extraversion;

	/** Openness. */
	private Double openness;

	/** Emotional. */
	private Double emotional;

	/**
	 * 생성자.
	 */
	public Personality() {
	}

	/**
	 * PER_ID을 설정합니다..
	 * 
	 * @param perId
	 *            PER_ID
	 */
	public void setPerId(String perId) {
		this.perId = perId;
	}

	/**
	 * PER_ID을 가져옵니다..
	 * 
	 * @return PER_ID
	 */
	public String getPerId() {
		return this.perId;
	}

	/**
	 * JOB을 설정합니다..
	 * 
	 * @param job
	 *            JOB
	 */
	public void setJobid(String jobid) {
		this.jobid = jobid;
	}

	/**
	 * JOB을 가져옵니다..
	 * 
	 * @return JOB
	 */
	public String getJobid() {
		return this.jobid;
	}

	/**
	 * 개인유저을 설정합니다..
	 * 
	 * @param applicant
	 *            개인유저
	 */
	public void setApplicantid(String applicantid) {
		this.applicantid = applicantid;
	}

	/**
	 * 개인유저을 가져옵니다..
	 * 
	 * @return 개인유저
	 */
	public String getApplicantid() {
		return this.applicantid;
	}

	/**
	 * Agreeableness을 설정합니다..
	 * 
	 * @param agreeableness
	 *            Agreeableness
	 */
	public void setAgreeableness(Double agreeableness) {
		this.agreeableness = agreeableness;
	}

	/**
	 * Agreeableness을 가져옵니다..
	 * 
	 * @return Agreeableness
	 */
	public Double getAgreeableness() {
		return this.agreeableness;
	}

	/**
	 * Conscientiousness을 설정합니다..
	 * 
	 * @param conscientiousness
	 *            Conscientiousness
	 */
	public void setConscientiousness(Double conscientiousness) {
		this.conscientiousness = conscientiousness;
	}

	/**
	 * Conscientiousness을 가져옵니다..
	 * 
	 * @return Conscientiousness
	 */
	public Double getConscientiousness() {
		return this.conscientiousness;
	}

	/**
	 * Extraversion을 설정합니다..
	 * 
	 * @param extraversion
	 *            Extraversion
	 */
	public void setExtraversion(Double extraversion) {
		this.extraversion = extraversion;
	}

	/**
	 * Extraversion을 가져옵니다..
	 * 
	 * @return Extraversion
	 */
	public Double getExtraversion() {
		return this.extraversion;
	}

	/**
	 * Openness을 설정합니다..
	 * 
	 * @param openness
	 *            Openness
	 */
	public void setOpenness(Double openness) {
		this.openness = openness;
	}

	/**
	 * Openness을 가져옵니다..
	 * 
	 * @return Openness
	 */
	public Double getOpenness() {
		return this.openness;
	}

	/**
	 * Emotional을 설정합니다..
	 * 
	 * @param emotional
	 *            Emotional
	 */
	public void setEmotional(Double emotional) {
		this.emotional = emotional;
	}

	/**
	 * Emotional을 가져옵니다..
	 * 
	 * @return Emotional
	 */
	public Double getEmotional() {
		return this.emotional;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((perId == null) ? 0 : perId.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		Personality other = (Personality) obj;
		if (perId == null) {
			if (other.perId != null) {
				return false;
			}
		} else if (!perId.equals(other.perId)) {
			return false;
		}
		return true;
	}

	@Override
	public String toString() {
		return "Personality [perId=" + perId + ", jobid=" + jobid + ", applicantid=" + applicantid + ", agreeableness="
				+ agreeableness + ", conscientiousness=" + conscientiousness + ", extraversion=" + extraversion
				+ ", openness=" + openness + ", emotional=" + emotional + "]";
	}
}
