package link.vo;

import java.io.Serializable;

/**
 * QUESTIONS 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Questions implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** QID. */
	private String qid;

	/** QUESTION. */
	private String question;

	/** CATEGORY. */
	private String category;

	/** SUBCATEGORY. */
	private String subcategory;

	/**
	 * 생성자.
	 */
	public Questions() {
	}

	/**
	 * QID을 설정합니다..
	 * 
	 * @param qid
	 *            QID
	 */
	public void setQid(String qid) {
		this.qid = qid;
	}

	/**
	 * QID을 가져옵니다..
	 * 
	 * @return QID
	 */
	public String getQid() {
		return this.qid;
	}

	/**
	 * QUESTION을 설정합니다..
	 * 
	 * @param question
	 *            QUESTION
	 */
	public void setQuestion(String question) {
		this.question = question;
	}

	/**
	 * QUESTION을 가져옵니다..
	 * 
	 * @return QUESTION
	 */
	public String getQuestion() {
		return this.question;
	}

	/**
	 * CATEGORY을 설정합니다..
	 * 
	 * @param category
	 *            CATEGORY
	 */
	public void setCategory(String category) {
		this.category = category;
	}

	/**
	 * CATEGORY을 가져옵니다..
	 * 
	 * @return CATEGORY
	 */
	public String getCategory() {
		return this.category;
	}

	/**
	 * SUBCATEGORY을 설정합니다..
	 * 
	 * @param subcategory
	 *            SUBCATEGORY
	 */
	public void setSubcategory(String subcategory) {
		this.subcategory = subcategory;
	}

	/**
	 * SUBCATEGORY을 가져옵니다..
	 * 
	 * @return SUBCATEGORY
	 */
	public String getSubcategory() {
		return this.subcategory;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((qid == null) ? 0 : qid.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		Questions other = (Questions) obj;
		if (qid == null) {
			if (other.qid != null) {
				return false;
			}
		} else if (!qid.equals(other.qid)) {
			return false;
		}
		return true;
	}

	@Override
	public String toString() {
		return "Questions [qid=" + qid + ", question=" + question + ", category=" + category + ", subcategory="
				+ subcategory + "]";
	}
	
	

}
