package link.vo;

import java.io.Serializable;
import java.util.Date;

/**
 * 새 테이블 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Skills implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** skillID. */
	private String skillid;

	/** 개인유저. */
	private String applicantid;

	/** JOB. */
	private String jobid;

	/** skillname. */
	private String skillname;

	/** skilllevel. */
	private String skilllevel;

	/** CERTNAME. */
	private String certname;

	/** CERTDATE. */
	private String certdate;

	/** CERTFROM. */
	private String certfrom;

	/**
	 * 생성자.
	 */
	public Skills() {
	}

	/**
	 * skillID을 설정합니다..
	 * 
	 * @param skillid
	 *            skillID
	 */
	public void setSkillid(String skillid) {
		this.skillid = skillid;
	}

	/**
	 * skillID을 가져옵니다..
	 * 
	 * @return skillID
	 */
	public String getSkillid() {
		return this.skillid;
	}

	/**
	 * 개인유저을 설정합니다..
	 * 
	 * @param applicant
	 *            개인유저
	 */
	public void setApplicantid(String applicantid) {
		this.applicantid = applicantid;
	}

	/**
	 * 개인유저을 가져옵니다..
	 * 
	 * @return 개인유저
	 */
	public String getApplicantid() {
		return this.applicantid;
	}

	/**
	 * JOB을 설정합니다..
	 * 
	 * @param job
	 *            JOB
	 */
	public void setJobid(String jobid) {
		this.jobid = jobid;
	}

	/**
	 * JOB을 가져옵니다..
	 * 
	 * @return JOB
	 */
	public String getJobid() {
		return this.jobid;
	}

	/**
	 * skillname을 설정합니다..
	 * 
	 * @param skillname
	 *            skillname
	 */
	public void setSkillname(String skillname) {
		this.skillname = skillname;
	}

	/**
	 * skillname을 가져옵니다..
	 * 
	 * @return skillname
	 */
	public String getSkillname() {
		return this.skillname;
	}

	/**
	 * skilllevel을 설정합니다..
	 * 
	 * @param skilllevel
	 *            skilllevel
	 */
	public void setSkilllevel(String skilllevel) {
		this.skilllevel = skilllevel;
	}

	/**
	 * skilllevel을 가져옵니다..
	 * 
	 * @return skilllevel
	 */
	public String getSkilllevel() {
		return this.skilllevel;
	}

	/**
	 * CERTNAME을 설정합니다..
	 * 
	 * @param certname
	 *            CERTNAME
	 */
	public void setCertname(String certname) {
		this.certname = certname;
	}

	/**
	 * CERTNAME을 가져옵니다..
	 * 
	 * @return CERTNAME
	 */
	public String getCertname() {
		return this.certname;
	}

	/**
	 * CERTDATE을 설정합니다..
	 * 
	 * @param certdate
	 *            CERTDATE
	 */
	public void setCertdate(String certdate) {
		this.certdate = certdate;
	}

	/**
	 * CERTDATE을 가져옵니다..
	 * 
	 * @return CERTDATE
	 */
	public String getCertdate() {
		return this.certdate;
	}

	/**
	 * CERTFROM을 설정합니다..
	 * 
	 * @param certfrom
	 *            CERTFROM
	 */
	public void setCertfrom(String certfrom) {
		this.certfrom = certfrom;
	}

	/**
	 * CERTFROM을 가져옵니다..
	 * 
	 * @return CERTFROM
	 */
	public String getCertfrom() {
		return this.certfrom;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((skillid == null) ? 0 : skillid.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		Skills other = (Skills) obj;
		if (skillid == null) {
			if (other.skillid != null) {
				return false;
			}
		} else if (!skillid.equals(other.skillid)) {
			return false;
		}
		return true;
	}

	@Override
	public String toString() {
		return "Skills [skillid=" + skillid + ", applicantid=" + applicantid + ", jobid=" + jobid + ", skillname="
				+ skillname + ", skilllevel=" + skilllevel + ", certname=" + certname + ", certdate=" + certdate
				+ ", certfrom=" + certfrom + "]";
	}
	
}
