
/* Drop Indexes */

DROP INDEX SYS_C007379;
DROP INDEX SYS_C007385;

commit


/* Drop Tables */
DROP TABLE HR.SELFPROMOTION CASCADE CONSTRAINTS;
DROP TABLE HR.CULTURE CASCADE CONSTRAINTS;
DROP TABLE HR.EDUCATION CASCADE CONSTRAINTS;
DROP TABLE HR.EXPERIENCE CASCADE CONSTRAINTS;
DROP TABLE HR.MATCHING CASCADE CONSTRAINTS;
DROP TABLE HR.PERSONALITY CASCADE CONSTRAINTS;
DROP TABLE HR.SKILLS CASCADE CONSTRAINTS;
DROP TABLE HR.APPLICANT CASCADE CONSTRAINTS;
DROP TABLE HR.CERTINDEX CASCADE CONSTRAINTS;
DROP TABLE HR.JOB CASCADE CONSTRAINTS;
DROP TABLE HR.COMPANY CASCADE CONSTRAINTS;
DROP TABLE HR.CULTURERESULT CASCADE CONSTRAINTS;
DROP TABLE HR.PERSONALITYRESULT CASCADE CONSTRAINTS;
DROP TABLE HR.QUESTIONS CASCADE CONSTRAINTS;
DROP TABLE HR.SKILLINDEX CASCADE CONSTRAINTS;



/* Drop Sequences */

DROP SEQUENCE HR.CULTUREID_SEQ;
DROP SEQUENCE HR.DEPARTMENTS_SEQ;
DROP SEQUENCE HR.JOBID_SEQ;
DROP SEQUENCE HR.PER_SEQ;
DROP SEQUENCE HR.SKILL_SEQ;
DROP SEQUENCE HR.SELF_SEQ;



/* Create Sequences */

CREATE SEQUENCE HR.CULTUREID_SEQ INCREMENT BY 1 MINVALUE 1 MAXVALUE 9999999999999999999999999999 START WITH 1001 CACHE 20;
CREATE SEQUENCE HR.JOBID_SEQ INCREMENT BY 1 MINVALUE 1 MAXVALUE 9999999999999999999999999999 START WITH 1001 CACHE 20;
CREATE SEQUENCE HR.PER_SEQ INCREMENT BY 1 MINVALUE 1 MAXVALUE 9999999999999999999999999999 START WITH 1001 CACHE 20;
CREATE SEQUENCE HR.SKILL_SEQ INCREMENT BY 1 MINVALUE 1 MAXVALUE 9999999999999999999999999999 START WITH 1001 CACHE 20;


/* Create Tables */

CREATE TABLE SELFPROMOTION
(
	JOBID varchar2(50 char) NOT NULL,
	QNUMBER number(2) NOT NULL,
	QUESTION clob,
	APPLICANTID varchar2(50 char),
	ANSWER clob,
	-- 입력문자열 최대값
	MAXTEXT number,
	-- 입력문자열 최소값
	-- 
	MINTEXT number,
	PRIMARY KEY (JOBID, QNUMBER)
);


CREATE TABLE HR.APPLICANT
(
	APPLICANTID varchar2(50 char) NOT NULL,
	APPLICANTFIRST varchar2(40 char) NOT NULL,
	APPLICANTLAST varchar2(40 char) NOT NULL,
	APPLICANTPHONE varchar2(15 char) NOT NULL,
	APPLICANTPASSWORD varchar2(20 char) NOT NULL,
	APPLICANTBDAY date NOT NULL,
	APPLICANTGENDER char(1 char) NOT NULL,
	APPLICANTVALID char(1 char) NOT NULL,
	CONSTRAINT SYS_C007357 PRIMARY KEY (APPLICANTID)
);


CREATE TABLE HR.CERTINDEX
(
	NAME varchar2(200 char) NOT NULL,
	CONSTRAINT SYS_C007359 PRIMARY KEY (NAME)
);


CREATE TABLE HR.COMPANY
(
	COMPID varchar2(50 char) NOT NULL,
	COMPPASSWORD varchar2(20 char) NOT NULL,
	COMPNAME varchar2(200 char) NOT NULL,
	COMPADDRESS varchar2(1000 char) NOT NULL,
	COMPAREA varchar2(50 char) NOT NULL,
	COMPSIZE number(7,0) NOT NULL,
	COMPVALID char(1 char) NOT NULL,
	COMPPHONE varchar2(20 char) NOT NULL,
	COMPNUM varchar2(20 char),
	CONSTRAINT SYS_C007368 PRIMARY KEY (COMPID)
);


CREATE TABLE HR.CULTURE
(
	CULTUREID varchar2(20 char) NOT NULL,
	APPLICANTID varchar2(50 char),
	COMPID varchar2(50 char),
	NEEDHARMONY number(5,4),
	NEEDCURIOSITY number(5,4),
	NEEDIDEAL number(5,4),
	NEEDCLOSENESS number(5,4),
	NEEDSELFEXPRESSION number(5,4),
	NEEDLIBERTY number(5,4),
	NEEDLOVE number(5,4),
	NEEDPRACTICALITY number(5,4),
	NEEDSTABILITY number(5,4),
	NEEDCHALLENGE number(5,4),
	NEEDSTRUCTURE number(5,4),
	CONSTRAINT SYS_C007370 PRIMARY KEY (CULTUREID)
);


CREATE TABLE HR.CULTURERESULT
(
	CATEGORY varchar2(200) NOT NULL,
	DETAIL clob,
	CONSTRAINT SYS_C007372 PRIMARY KEY (CATEGORY)
);


CREATE TABLE HR.EDUCATION
(
	APPLICANTID varchar2(50 char) NOT NULL,
	NAME varchar2(500 char) NOT NULL,
	MAJOR varchar2(500 char) NOT NULL,
	MINOR varchar2(500 char),
	DIPLOMA varchar2(20 char) NOT NULL,
	STARTDATE date NOT NULL,
	ENDDATE date NOT NULL,
	CONSTRAINT SYS_C007379 PRIMARY KEY (APPLICANTID, NAME, MAJOR, DIPLOMA)
);


CREATE TABLE HR.EXPERIENCE
(
	APPLICANTID varchar2(50 char) NOT NULL,
	WORKNAME varchar2(500 char) NOT NULL,
	WORKJOBTITLE varchar2(500 char) NOT NULL,
	STARTDATE date NOT NULL,
	ENDDATE date NOT NULL,
	CONSTRAINT SYS_C007385 PRIMARY KEY (APPLICANTID, WORKNAME, WORKJOBTITLE)
);

CREATE TABLE HR.JOB
(
	JOBID varchar2(50 char) NOT NULL,
	COMPID varchar2(50 char) NOT NULL,
	JOBTITLE varchar2(500 char),
	JOBDESC clob,
	JOBTO number(3,0),
	JOBAPPLIED number(3,0),
	JOBSTART date,
	JOBEND date,
	EDUMAJOR varchar2(500 char),
	EDULEVEL char(1 char),
	EXPAREA varchar2(500 char),
	EXPLEVEL char(1 char),
	-- 경력기간
	-- 
	EXPDURATION number,
	CONSTRAINT SYS_C007388 PRIMARY KEY (JOBID)
);

CREATE TABLE HR.MATCHING
(
	APPLICANTID varchar2(50 char) NOT NULL,
	JOBID varchar2(50 char) NOT NULL,
	CULPER number(5,4),
	SKILLPER number(5,4),
	PERPER number(5,4),
	TOTALPER number(5,4),
	STATUS varchar2(5 char),
	CONSTRAINT SYS_C007391 PRIMARY KEY (APPLICANTID, JOBID)
);


CREATE TABLE HR.PERSONALITY
(
	PERID varchar2(20 char) NOT NULL,
	JOBID varchar2(50 char),
	APPLICANTID varchar2(50 char),
	AGREEABLENESS number(5,4),
	CONSCIENTIOUSNESS number(5,4),
	EXTRAVERSION number(5,4),
	OPENNESS number(5,4),
	EMOTIONAL number(5,4),
	CONSTRAINT SYS_C007393 PRIMARY KEY (PERID)
);


CREATE TABLE HR.PERSONALITYRESULT
(
	CATEGORY varchar2(2000) NOT NULL,
	DETAIL clob,
	CONSTRAINT SYS_C007395 PRIMARY KEY (CATEGORY)
);


CREATE TABLE HR.QUESTIONS
(
	QID number(3,0) NOT NULL,
	QUESTION varchar2(500 char) NOT NULL,
	CATEGORY varchar2(20 char) NOT NULL,
	SCORE varchar2(20 char),
	CONSTRAINT SYS_C007399 PRIMARY KEY (QID)
);


CREATE TABLE HR.SKILLINDEX
(
	NAME varchar2(500 char) NOT NULL,
	CONSTRAINT SYS_C007401 PRIMARY KEY (NAME)
);


CREATE TABLE HR.SKILLS
(
	SKILLID varchar2(20 char) NOT NULL,
	APPLICANTID varchar2(50 char),
	JOBID varchar2(50 char),
	SKILLNAME varchar2(500 char),
	SKILLLEVEL char(1 char),
	CERTNAME varchar2(500 char),
	CERTDATE date,
	CERTFROM varchar2(20 char),
	CONSTRAINT SYS_C007403 PRIMARY KEY (SKILLID)
);



/* Create Foreign Keys */

ALTER TABLE SELFPROMOTION
	ADD FOREIGN KEY (APPLICANTID)
	REFERENCES HR.APPLICANT (APPLICANTID)
;


ALTER TABLE HR.CULTURE
	ADD CONSTRAINT SYS_C007410 FOREIGN KEY (APPLICANTID)
	REFERENCES HR.APPLICANT (APPLICANTID)
;


ALTER TABLE HR.EDUCATION
	ADD CONSTRAINT SYS_C007411 FOREIGN KEY (APPLICANTID)
	REFERENCES HR.APPLICANT (APPLICANTID)
;


ALTER TABLE HR.EXPERIENCE
	ADD CONSTRAINT SYS_C007412 FOREIGN KEY (APPLICANTID)
	REFERENCES HR.APPLICANT (APPLICANTID)
;


ALTER TABLE HR.MATCHING
	ADD CONSTRAINT SYS_C007413 FOREIGN KEY (APPLICANTID)
	REFERENCES HR.APPLICANT (APPLICANTID)
;


ALTER TABLE HR.PERSONALITY
	ADD CONSTRAINT SYS_C007414 FOREIGN KEY (APPLICANTID)
	REFERENCES HR.APPLICANT (APPLICANTID)
;


ALTER TABLE HR.SKILLS
	ADD CONSTRAINT SYS_C007415 FOREIGN KEY (APPLICANTID)
	REFERENCES HR.APPLICANT (APPLICANTID)
;


ALTER TABLE HR.CULTURE
	ADD CONSTRAINT SYS_C007416 FOREIGN KEY (COMPID)
	REFERENCES HR.COMPANY (COMPID)
;


ALTER TABLE HR.JOB
	ADD CONSTRAINT SYS_C007417 FOREIGN KEY (COMPID)
	REFERENCES HR.COMPANY (COMPID)
;


ALTER TABLE SELFPROMOTION
	ADD FOREIGN KEY (JOBID)
	REFERENCES HR.JOB (JOBID)
;


ALTER TABLE HR.MATCHING
	ADD CONSTRAINT SYS_C007418 FOREIGN KEY (JOBID)
	REFERENCES HR.JOB (JOBID)
;


ALTER TABLE HR.PERSONALITY
	ADD CONSTRAINT SYS_C007419 FOREIGN KEY (JOBID)
	REFERENCES HR.JOB (JOBID)
;


ALTER TABLE HR.SKILLS
	ADD CONSTRAINT SYS_C007420 FOREIGN KEY (JOBID)
	REFERENCES HR.JOB (JOBID)
;



/* Create Indexes */

CREATE UNIQUE INDEX SYS_C007379 ON HR.EDUCATION (APPLICANTID, NAME, MAJOR, DIPLOMA);
CREATE UNIQUE INDEX SYS_C007385 ON HR.EXPERIENCE (APPLICANTID, WORKNAME, WORKJOBTITLE);



/* Comments */

COMMENT ON COLUMN SELFPROMOTION.MAXTEST IS '입력문자열 최대값';
COMMENT ON COLUMN SELFPROMOTION.MINTEXT IS '입력문자열 최소값
';
COMMENT ON COLUMN HR.JOB.EXPSTARTPERIOD IS '업무시작일
';



